apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"web-app-in-eap-on-ocp:latest","namespace":"eap-ocp"},"fieldPath":"spec.template.spec.containers[?(@.name==\"web-app-in-eap-on-ocp\")].image"}]'
  labels:
    app: my-app
  name: my-app
  namespace: eap-ocp
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: my-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: my-app
    spec:
      containers:
      - image: web-app-in-eap-on-ocp:latest
        imagePullPolicy: IfNotPresent
        name: web-app-in-eap-on-ocp
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
      restartPolicy: Always
