apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: web-app-in-eap-on-ocp
  namespace: eap-ocp
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "default-route-openshift-image-registry.apps.cluster-fvw6c.fvw6c.sandbox1281.opentlc.com/eap-ocp/web-app-in-eap-on-ocp"
      importPolicy:
        scheduled: true
