apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: web-app-in-eap-on-ocp
  namespace: eap-ocp
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/obryan5598/web-app-in-eap-on-ocp:latest"
      importPolicy:
        scheduled: true
