apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: eap-ocp
spec:
  host: my-app-eap-ocp.apps.cluster-fvw6c.fvw6c.sandbox1281.opentlc.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: my-app
    weight: 100
  wildcardPolicy: None
